@startuml


class Authentication {
 Authentication Functionalities
}
'class AppUser {
'
'}
'
'class AuthenticationController {
'    + register(request: AuthenticationRequestModel): ResponseEntity
'    + authenticate(request: AuthenticationRequestModel): ResponseEntity<AuthenticationResponseModel>
'}
footer Authentication microservice UML class diagram
@enduml