@startuml

class Order {
    - pizzaList: List<Pizza>
    - orderID: Integer
    - userID: Integer
    - pickupTime: LocalDateTime
    - storeID: Integer
    - price: Double
    - couponList: List<Coupon>
    --
    getters & setters...
    + calculatePrice(): Double
}

class OrderAPI {
    + createOrder(token: String, order: Order): Order
    + editOrder(token: String, order: Order): Order
    + deleteOrder(token: String, order: Order): Boolean
    + getOrders(token: String, user: Integer): List<Order>
    + getOrdersAdmin(token: String): List<Order>
    + notifyOrderCreated(order: Order): Boolean
    + notifyOrderChanged(order: Order): Boolean
    + notifyOrderDeleted(orderID: Integer): Boolean
}

footer Order microservice UML class diagram
@enduml