@startuml

abstract class User {
   - id: Integer
   - role: String
   - allergies: List<Allergy>
   - 
   --
   + createUser(role, allergies): Void
   + editAllergies(List<Allergy>): Void
   + deleteAccount(): Boolean
   getters & setters ...
}

class Manager extends User {

}

class Employee extends User {

}

class Custommer extends User {

}

interface UserRepository

UserRepository -- User

footer Order microservice UML class diagram
@enduml
